import express from 'express';
import { AuthService } from '../src/services/auth.service.js';
import { AuthRepository } from '../src/repositories/auth.repository.js';
import { AuthController } from '../src/controllers/auth.controller.js';
import { prisma } from '../models/index.js';
const router = express.Router();
const authRepository = new AuthRepository(prisma);
const authService = new AuthService(authRepository);
const authController = new AuthController(authService);
router.post('/token', authController.autoLogin);
export default router;
